/**
 * Placeholder / dummy data untuk Dashboard Bandung
 * Semua angka ILUSTRATIF — menunggu integrasi data resmi dari
 * Diskominfo / BPS / Disdukcapil Kota Bandung.
 *
 * Referensi: README.txt §Fidelity + .dc.html state data
 */

import type {
  CategorySummary,
  Dataset,
  Sector,
  KecamatanData,
  AgeBand,
  DinasBudget,
  SectorDetail,
} from "@/types/dataset";

// ─── Kategori (kompatibel dengan BE existing) ─────────────────────────────────

export const CATEGORY_PLACEHOLDERS: CategorySummary[] = [
  { slug: "kependudukan", name: "Kependudukan", description: "Jumlah, distribusi, dan komposisi penduduk per kecamatan.", datasetCount: 3 },
  { slug: "ekonomi", name: "Ekonomi", description: "Indikator ekonomi, UMKM, dan aktivitas perdagangan kota.", datasetCount: 2 },
  { slug: "kesehatan", name: "Kesehatan", description: "Fasilitas kesehatan, layanan puskesmas, dan data kasus.", datasetCount: 2 },
  { slug: "infrastruktur", name: "Infrastruktur", description: "Jalan, transportasi publik, dan fasilitas umum kota.", datasetCount: 2 },
  { slug: "lingkungan", name: "Lingkungan Hidup", description: "Kualitas udara, ruang terbuka hijau, dan pengelolaan sampah.", datasetCount: 2 },
  { slug: "pendidikan", name: "Pendidikan", description: "Sekolah, angka partisipasi, dan fasilitas pendidikan.", datasetCount: 2 },
];

export const DATASET_PLACEHOLDERS: Record<string, Dataset[]> = {
  kependudukan: [
    { id: 1, categoryId: 1, sourceId: "jumlah-penduduk-per-kecamatan", name: "Jumlah Penduduk per Kecamatan", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/jumlah-penduduk-per-kecamatan", syncFrequency: "monthly", lastSyncedAt: "2026-06-01T00:00:00.000Z" },
    { id: 2, categoryId: 1, sourceId: "kepadatan-penduduk", name: "Kepadatan Penduduk", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/kepadatan-penduduk", syncFrequency: "monthly", lastSyncedAt: "2026-06-01T00:00:00.000Z" },
    { id: 3, categoryId: 1, sourceId: "komposisi-usia-penduduk", name: "Komposisi Usia Penduduk", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/komposisi-usia-penduduk", syncFrequency: "monthly", lastSyncedAt: null },
  ],
  ekonomi: [
    { id: 4, categoryId: 2, sourceId: "data-umkm-kota-bandung", name: "Data UMKM Kota Bandung", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/data-umkm", syncFrequency: "monthly", lastSyncedAt: "2026-05-01T00:00:00.000Z" },
    { id: 5, categoryId: 2, sourceId: "pdrb-kota-bandung", name: "PDRB Kota Bandung", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/pdrb", syncFrequency: "monthly", lastSyncedAt: null },
  ],
  kesehatan: [
    { id: 6, categoryId: 3, sourceId: "fasilitas-kesehatan", name: "Fasilitas Kesehatan", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/fasilitas-kesehatan", syncFrequency: "monthly", lastSyncedAt: "2026-06-01T00:00:00.000Z" },
    { id: 7, categoryId: 3, sourceId: "kunjungan-puskesmas", name: "Kunjungan Puskesmas", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/kunjungan-puskesmas", syncFrequency: "weekly", lastSyncedAt: "2026-06-24T00:00:00.000Z" },
  ],
  infrastruktur: [
    { id: 8, categoryId: 4, sourceId: "kondisi-jalan", name: "Kondisi Jalan Kota", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/kondisi-jalan", syncFrequency: "monthly", lastSyncedAt: "2026-05-01T00:00:00.000Z" },
    { id: 9, categoryId: 4, sourceId: "trayek-transportasi-umum", name: "Trayek Transportasi Umum", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/trayek-transportasi", syncFrequency: "monthly", lastSyncedAt: null },
  ],
  lingkungan: [
    { id: 10, categoryId: 5, sourceId: "kualitas-udara", name: "Kualitas Udara (ISPU)", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/kualitas-udara", syncFrequency: "weekly", lastSyncedAt: "2026-06-24T00:00:00.000Z" },
    { id: 11, categoryId: 5, sourceId: "ruang-terbuka-hijau", name: "Ruang Terbuka Hijau", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/rth", syncFrequency: "monthly", lastSyncedAt: "2026-06-01T00:00:00.000Z" },
  ],
  pendidikan: [
    { id: 12, categoryId: 6, sourceId: "data-sekolah", name: "Data Sekolah", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/data-sekolah", syncFrequency: "monthly", lastSyncedAt: "2026-06-01T00:00:00.000Z" },
    { id: 13, categoryId: 6, sourceId: "angka-partisipasi-sekolah", name: "Angka Partisipasi Sekolah", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/angka-partisipasi", syncFrequency: "monthly", lastSyncedAt: null },
  ],
};

// ─── 8 Sektor untuk Home & Topics ─────────────────────────────────────────────

export const SECTORS: Sector[] = [
  {
    id: "kependudukan",
    code: "DUK",
    name: "Kependudukan",
    desc: "Jumlah, kepadatan, dan sebaran penduduk Kota Bandung di 30 kecamatan.",
    stat: "2,52 Juta jiwa",
    color: "#1F5AA8",
    tint: "#E8F0FA",
    cluster: "sosial",
    spark: [2380, 2400, 2430, 2450, 2470, 2490, 2510, 2520],
    statusLabel: "Data Terkini",
    statusColor: "#1D8348",
    statusBg: "#E7F6ED",
  },
  {
    id: "ekonomi",
    code: "EKO",
    name: "Ekonomi & UMKM",
    desc: "Indikator ekonomi, PDRB, dan data UMKM aktif Kota Bandung.",
    stat: "142.500 UMKM",
    color: "#E8821E",
    tint: "#FDEEDD",
    cluster: "gov",
    spark: [130000, 133000, 136000, 138000, 140000, 141000, 142500, 142500],
    statusLabel: "Perlu Perhatian",
    statusColor: "#E8821E",
    statusBg: "#FDEEDD",
  },
  {
    id: "kesehatan",
    code: "KES",
    name: "Kesehatan",
    desc: "Fasilitas kesehatan, kunjungan puskesmas, dan layanan kesehatan masyarakat.",
    stat: "73 Puskesmas",
    color: "#1D8348",
    tint: "#E7F6ED",
    cluster: "sosial",
    spark: [68, 69, 70, 71, 72, 72, 73, 73],
    statusLabel: "Data Terkini",
    statusColor: "#1D8348",
    statusBg: "#E7F6ED",
  },
  {
    id: "pendidikan",
    code: "PDK",
    name: "Pendidikan",
    desc: "Sekolah, angka partisipasi sekolah, dan fasilitas pendidikan kota.",
    stat: "10,8 Thn rata-rata",
    color: "#F0B429",
    tint: "#FDF3DA",
    cluster: "sosial",
    spark: [9.8, 10.0, 10.2, 10.4, 10.5, 10.6, 10.7, 10.8],
    statusLabel: "Data Terkini",
    statusColor: "#1D8348",
    statusBg: "#E7F6ED",
  },
  {
    id: "infrastruktur",
    code: "INF",
    name: "Infrastruktur",
    desc: "Kondisi jalan, trayek transportasi umum, dan fasilitas umum kota.",
    stat: "82% jalan baik",
    color: "#4C5D6B",
    tint: "#F4F6F9",
    cluster: "fisik",
    spark: [74, 76, 77, 78, 79, 80, 81, 82],
    statusLabel: "Perlu Perhatian",
    statusColor: "#E8821E",
    statusBg: "#FDEEDD",
  },
  {
    id: "lingkungan",
    code: "LNG",
    name: "Lingkungan Hidup",
    desc: "Kualitas udara ISPU, ruang terbuka hijau, dan pengelolaan sampah kota.",
    stat: "12 kec. udara baik",
    color: "#1D8348",
    tint: "#E7F6ED",
    cluster: "fisik",
    spark: [6, 7, 8, 9, 10, 11, 12, 12],
    statusLabel: "Data Terkini",
    statusColor: "#1D8348",
    statusBg: "#E7F6ED",
  },
  {
    id: "anggaran",
    code: "ANG",
    name: "Anggaran & Keuangan",
    desc: "Realisasi APBD, belanja per OPD, dan transparansi keuangan Pemkot Bandung.",
    stat: "78% realisasi APBD",
    color: "#1F5AA8",
    tint: "#E8F0FA",
    cluster: "gov",
    spark: [60, 63, 66, 68, 70, 73, 76, 78],
    statusLabel: "On Track",
    statusColor: "#1D8348",
    statusBg: "#E7F6ED",
  },
  {
    id: "sosial",
    code: "SOS",
    name: "Sosial & Kemasyarakatan",
    desc: "Data kemiskinan, bansos, penyandang disabilitas, dan layanan sosial kota.",
    stat: "3,2% tingkat kemiskinan",
    color: "#C0392B",
    tint: "#FBEAE8",
    cluster: "sosial",
    spark: [4.1, 3.9, 3.8, 3.7, 3.6, 3.4, 3.3, 3.2],
    statusLabel: "Perlu Perhatian",
    statusColor: "#E8821E",
    statusBg: "#FDEEDD",
  },
];

// ─── Tren populasi 2016–2026 ───────────────────────────────────────────────────

export const POPULATION_YEARS = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026];

export const POPULATION_TREND = [2380000, 2400000, 2420000, 2440000, 2450000, 2460000, 2475000, 2490000, 2500000, 2510000, 2520000];

// ─── 30 Kecamatan ─────────────────────────────────────────────────────────────

function densityColor(v: number): string {
  if (v < 9000) return "#DCEAFB";
  if (v < 12000) return "#AECBEE";
  if (v < 15000) return "#6FA0D8";
  if (v < 18000) return "#3D74B8";
  return "#1F4E8C";
}

function populationColor(p: number): string {
  if (p < 200000) return "#DCEAFB";
  if (p < 320000) return "#AECBEE";
  if (p < 440000) return "#6FA0D8";
  if (p < 560000) return "#3D74B8";
  return "#1F4E8C";
}

const rawKecamatan: [string, number, number][] = [
  ["Andir", 18500, 592000], ["Antapani", 15200, 412000], ["Arcamanik", 11800, 378000], ["Astanaanyar", 19800, 489000],
  ["Babakan Ciparay", 17600, 631000], ["Bandung Kidul", 10200, 254000], ["Bandung Kulon", 19200, 587000], ["Bandung Wetan", 9800, 142000],
  ["Batununggal", 16400, 548000], ["Bojongloa Kaler", 20100, 601000], ["Bojongloa Kidul", 15900, 423000], ["Buahbatu", 13700, 398000],
  ["Cibeunying Kaler", 12100, 289000], ["Cibeunying Kidul", 14300, 462000], ["Cibiru", 9600, 268000], ["Cicendo", 14800, 391000],
  ["Cidadap", 8200, 231000], ["Cinambo", 7100, 159000], ["Coblong", 13400, 481000], ["Gedebage", 6800, 187000],
  ["Kiaracondong", 18200, 527000], ["Lengkong", 13900, 342000], ["Mandalajati", 10900, 276000], ["Panyileukan", 8600, 193000],
  ["Rancasari", 11200, 318000], ["Regol", 16800, 356000], ["Sukajadi", 15100, 412000], ["Sukasari", 10600, 298000],
  ["Sumur Bandung", 12600, 124000], ["Ujung Berung", 12900, 309000],
];

const totalPop = rawKecamatan.reduce((sum, k) => sum + k[2], 0);

export const KECAMATAN_DATA: KecamatanData[] = rawKecamatan.map(([name, val, pop]) => ({
  name,
  val,
  pop,
  share: ((pop / totalPop) * 100).toFixed(1),
  color: densityColor(val),
  colorPop: populationColor(pop),
}));

// ─── Age bands (komposisi usia) ────────────────────────────────────────────────

export const AGE_BANDS: AgeBand[] = [
  { label: "0–9", male: 72, female: 68 },
  { label: "10–19", male: 78, female: 74 },
  { label: "20–29", male: 85, female: 82 },
  { label: "30–39", male: 80, female: 79 },
  { label: "40–49", male: 70, female: 69 },
  { label: "50–59", male: 58, female: 60 },
  { label: "60+", male: 40, female: 48 },
];

// ─── Dinas budget (exec screen) ───────────────────────────────────────────────

export const DINAS_BUDGET: DinasBudget[] = [
  { name: "Dinas Pendidikan", pct: 85 },
  { name: "Dinas Kesehatan", pct: 78 },
  { name: "Dinas PUPR", pct: 72 },
  { name: "Dinas Sosial", pct: 65 },
  { name: "Diskominfo", pct: 90 },
  { name: "Dinas Lingkungan Hidup", pct: 58 },
];

// ─── Detail dummy per sektor (halaman /dashboard/[slug]) ──────────────────────

export const SECTOR_DETAILS: Record<string, SectorDetail> = {
  kependudukan: {
    kpis: [
      { label: "Total Penduduk", value: "2.520.000" },
      { label: "Kepadatan", value: "15.070/km²" },
      { label: "Rasio Jenis Kelamin", value: "99,2" },
      { label: "Laju Pertumbuhan", value: "+0,68%", accent: "green" },
    ],
    trend: POPULATION_TREND,
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: "Komposisi Usia Penduduk",
    breakdownLegendA: "Laki-laki",
    breakdownLegendB: "Perempuan",
    breakdownRows: AGE_BANDS.map((b) => ({ label: b.label, a: b.male, b: b.female })),
    kecamatanValueLabel: "Jumlah Penduduk",
    kecamatanUnit: "jiwa",
    kecamatanFactor: 1,
  },
  ekonomi: {
    kpis: [
      { label: "UMKM Aktif", value: "142.500" },
      { label: "PDRB", value: "Rp 214,3 T" },
      { label: "Pertumbuhan Ekonomi", value: "+5,4%", accent: "green" },
      { label: "Pengangguran Terbuka", value: "6,8%" },
    ],
    trend: [118000, 122000, 126000, 129000, 132000, 135000, 138000, 140000, 141500, 142000, 142500],
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: "UMKM per Sektor Usaha",
    breakdownLegendA: "Formal",
    breakdownLegendB: "Informal",
    breakdownRows: [
      { label: "Kuliner", a: 62, b: 84 },
      { label: "Fashion", a: 48, b: 72 },
      { label: "Kerajinan", a: 35, b: 58 },
      { label: "Jasa", a: 54, b: 66 },
      { label: "Perdagangan", a: 60, b: 90 },
      { label: "Pertanian", a: 22, b: 40 },
      { label: "Teknologi", a: 30, b: 20 },
    ],
    kecamatanValueLabel: "Jumlah UMKM",
    kecamatanUnit: "unit",
    kecamatanFactor: 0.24,
  },
  kesehatan: {
    kpis: [
      { label: "Fasilitas Kesehatan", value: "73 Puskesmas" },
      { label: "Kunjungan Bulanan", value: "182.400" },
      { label: "Angka Harapan Hidup", value: "74,2 Thn" },
      { label: "Angka Stunting", value: "8,3%" },
    ],
    trend: [155000, 160000, 163000, 167000, 171000, 174000, 177000, 179000, 180500, 181500, 182400],
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: "Jenis Layanan per Kelompok Usia",
    breakdownLegendA: "Rawat Jalan",
    breakdownLegendB: "Rawat Inap",
    breakdownRows: AGE_BANDS.map((b) => ({ label: b.label, a: b.male, b: Math.round(b.female * 0.3) })),
    kecamatanValueLabel: "Kunjungan Layanan Kesehatan",
    kecamatanUnit: "kunjungan/bln",
    kecamatanFactor: 0.31,
  },
  pendidikan: {
    kpis: [
      { label: "Jumlah Sekolah", value: "1.842" },
      { label: "Rata-rata Lama Sekolah", value: "10,8 Thn" },
      { label: "Angka Partisipasi Sekolah", value: "98,7%" },
      { label: "Guru Bersertifikasi", value: "76%" },
    ],
    trend: [9.8, 10.0, 10.2, 10.3, 10.4, 10.5, 10.6, 10.6, 10.7, 10.7, 10.8],
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: "Sekolah Negeri vs Swasta per Jenjang",
    breakdownLegendA: "Negeri",
    breakdownLegendB: "Swasta",
    breakdownRows: [
      { label: "PAUD", a: 22, b: 78 },
      { label: "SD", a: 68, b: 32 },
      { label: "SMP", a: 55, b: 45 },
      { label: "SMA", a: 48, b: 52 },
      { label: "SMK", a: 35, b: 65 },
      { label: "PT", a: 18, b: 82 },
    ],
    kecamatanValueLabel: "Jumlah Sekolah",
    kecamatanUnit: "sekolah",
    kecamatanFactor: 0.062,
  },
  infrastruktur: {
    kpis: [
      { label: "Kondisi Jalan Baik", value: "82%", accent: "green" },
      { label: "Total Panjang Jalan", value: "1.236 km" },
      { label: "Trayek Angkutan Umum", value: "39 Trayek" },
      { label: "Titik Lampu Jalan", value: "24.800" },
    ],
    trend: [74, 76, 77, 78, 79, 80, 80, 81, 81, 82, 82],
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: "Kondisi per Jenis Infrastruktur",
    breakdownLegendA: "Baik",
    breakdownLegendB: "Rusak",
    breakdownRows: [
      { label: "Jln. Nasional", a: 91, b: 9 },
      { label: "Jln. Provinsi", a: 85, b: 15 },
      { label: "Jln. Kota", a: 78, b: 22 },
      { label: "Jln. Lingk.", a: 66, b: 34 },
      { label: "Jembatan", a: 88, b: 12 },
      { label: "Trotoar", a: 60, b: 40 },
      { label: "Drainase", a: 70, b: 30 },
    ],
    kecamatanValueLabel: "Panjang Jalan",
    kecamatanUnit: "km",
    kecamatanFactor: 0.021,
  },
  lingkungan: {
    kpis: [
      { label: "Kualitas Udara Baik", value: "12 Kec." },
      { label: "Ruang Terbuka Hijau", value: "12,6%" },
      { label: "Sampah Terkelola", value: "1.450 ton/hari" },
      { label: "Titik Bank Sampah", value: "218", accent: "green" },
    ],
    trend: [6, 7, 8, 9, 10, 10, 11, 11, 12, 12, 12],
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: "Pengelolaan Sampah per Wilayah",
    breakdownLegendA: "Organik",
    breakdownLegendB: "Anorganik",
    breakdownRows: [
      { label: "Wil. 1", a: 58, b: 42 },
      { label: "Wil. 2", a: 55, b: 45 },
      { label: "Wil. 3", a: 61, b: 39 },
      { label: "Wil. 4", a: 50, b: 50 },
      { label: "Wil. 5", a: 64, b: 36 },
      { label: "Wil. 6", a: 47, b: 53 },
      { label: "Wil. 7", a: 53, b: 47 },
    ],
    kecamatanValueLabel: "Volume Sampah Terkelola",
    kecamatanUnit: "ton/hari",
    kecamatanFactor: 0.0023,
  },
  anggaran: {
    kpis: [
      { label: "Realisasi APBD", value: "78%", accent: "green" },
      { label: "Total APBD", value: "Rp 8,9 T" },
      { label: "Belanja Modal", value: "Rp 1,6 T" },
      { label: "SILPA", value: "Rp 412 M" },
    ],
    trend: [60, 63, 66, 68, 70, 72, 73, 75, 76, 77, 78],
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: "Realisasi Anggaran per Dinas",
    breakdownLegendA: "Terealisasi",
    breakdownLegendB: "Sisa",
    breakdownRows: DINAS_BUDGET.map((d) => ({ label: d.name, a: d.pct, b: 100 - d.pct })),
    kecamatanValueLabel: "Belanja per Kecamatan",
    kecamatanUnit: "Rp Juta",
    kecamatanFactor: 0.42,
  },
  sosial: {
    kpis: [
      { label: "Tingkat Kemiskinan", value: "3,2%" },
      { label: "Penerima Bansos", value: "48.200 KK" },
      { label: "Penyandang Disabilitas", value: "12.400 Jiwa" },
      { label: "Panti Sosial Aktif", value: "34" },
    ],
    trend: [4.1, 3.9, 3.8, 3.7, 3.6, 3.5, 3.4, 3.3, 3.3, 3.2, 3.2],
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: "Jenis Bantuan Sosial per Kategori",
    breakdownLegendA: "Tunai",
    breakdownLegendB: "Non-Tunai",
    breakdownRows: [
      { label: "Lansia", a: 62, b: 38 },
      { label: "Difabel", a: 55, b: 45 },
      { label: "Anak", a: 40, b: 60 },
      { label: "PKH", a: 70, b: 30 },
      { label: "BPNT", a: 15, b: 85 },
      { label: "Yatim Piatu", a: 48, b: 52 },
      { label: "Korban Bencana", a: 80, b: 20 },
    ],
    kecamatanValueLabel: "Penerima Bansos",
    kecamatanUnit: "KK",
    kecamatanFactor: 0.019,
  },
};

// ─── i18n strings (Indonesia-only — tidak ada fitur ganti bahasa) ─────────────

export const I18N = {
  utility_text: "Portal Resmi Pemerintah Kota Bandung",
  nav_home: "Beranda",
  nav_topics: "Topik & Sektor",
  nav_api: "Data API",
  btn_exec: "Login Eksekutif",
  tagline: "Satu Data, Satu Bandung",
  search_ph: 'Cari indikator, mis. "kepadatan penduduk"…',
  hero_eyebrow: "Portal Data Terbuka Kota Bandung",
  hero_title: "Dashboard Bandung",
  hero_sub: "Satu kanal angka, metrik, dan visualisasi data resmi Kota Bandung untuk warga dan pengambil kebijakan.",
  kpi_pop: "Populasi",
  kpi_area: "Luas Wilayah",
  kpi_kec: "Kecamatan",
  kpi_kel: "Kelurahan",
  kpi_pop_val: "2,52 Juta",
  kpi_area_val: "167,3 km²",
  kpi_kec_val: "30",
  kpi_kel_val: "151",
  sectors_title: "Jelajahi Data per Sektor",
  sectors_sub: "Pilih sektor untuk melihat indikator, tren, dan sebaran datanya.",
  detail_link: "Lihat semua",
  highlight_title: "Sorotan Data Minggu Ini",
  featured_title: "Dashboard Pilihan",
  featured_sub: "Pilihan dashboard dari berbagai topik yang bisa dijelajahi lebih lanjut.",
  explore_more: "Eksplor lebih banyak",
  highlight_section_title: "Highlight",
  carousel_prev: "Sebelumnya",
  carousel_next: "Berikutnya",
  data_year_label: "Data tahun",
  chart_trend_title: "Tren Jumlah Penduduk 2016–2026",
  growth_label: "Laju Pertumbuhan/th",
  cta_title: "Punya data yang ingin dipublikasikan?",
  cta_body: "Diskominfo Kota Bandung membuka kanal integrasi data untuk OPD dan mitra.",
  cta_btn: "Hubungi Kami",
  breadcrumb_home: "Beranda",
  breadcrumb_topics: "Topik & Sektor",
  topics_h1: "Topik & Sektor",
  topics_sub: "Jelajahi seluruh indikator resmi Kota Bandung, dikelompokkan per sektor.",
  topics_search_ph: "Cari dashboard…",
  filter_semua: "Semua",
  filter_gov: "Pemerintahan & Ekonomi",
  filter_sosial: "Manusia & Sosial",
  filter_fisik: "Fisik & Lingkungan",
  sidebar_all_topics: "Semua Topik",
  dashboard_views: "dilihat",
  detail_link2: "Lihat Detail",
  detail_title: "Kependudukan",
  detail_desc: "Jumlah, kepadatan, dan sebaran penduduk Kota Bandung di 30 kecamatan.",
  detail_source: "Sumber",
  detail_updated: "Diperbarui",
  detail_download: "Unduh Data",
  source_name: "Disdukcapil Kota Bandung",
  updated_date: "Jun 2026",
  kpi_total_pop: "Total Penduduk",
  kpi_density: "Kepadatan",
  kpi_sexratio: "Rasio Jenis Kelamin",
  kpi_growth: "Laju Pertumbuhan",
  chart_age_title: "Komposisi Usia Penduduk",
  male_label: "Laki-laki",
  female_label: "Perempuan",
  related_title: "Indikator Terkait",
  map_dist_title: "Sebaran Penduduk per Kecamatan",
  table_title: "Data per Kecamatan",
  table_col_kec: "Kecamatan",
  table_col_pop: "Penduduk",
  table_col_density: "Kepadatan (jiwa/km²)",
  table_col_share: "% dari Total",
  dataset_loading: "Memuat dashboard…",
  dataset_empty: "Admin belum menambahkan dashboard untuk sektor ini.",
  api_req_h1: "Ajukan Permintaan API",
  api_req_sub: "Isi formulir berikut untuk mengajukan akses API Dashboard Bandung.",
  api_req_name: "Nama Pengaju",
  api_req_institution: "Instansi Pengaju",
  api_req_website: "Link Website yang Akan Menggunakan",
  api_req_email: "Email Pengaju",
  api_req_notes: "Catatan",
  api_req_submit: "Kirim Permohonan",
  api_req_submitting: "Mengirim…",
  api_req_success_title: "Permohonan Terkirim",
  api_req_success_body: "Permohonan Anda sedang diproses, kurang lebih 2 hari kerja. Informasi akan disampaikan melalui email, mohon cek email Anda secara berkala.",
  api_req_back: "Kembali ke Data API",
  api_req_error: "Gagal mengirim permohonan, coba lagi.",
  api_h1: "Akses Data via API",
  api_sub: "Ambil data Dashboard Bandung secara terprogram untuk aplikasi, riset, atau integrasi sistem Anda.",
  api_key_title: "Kunci API Anda",
  api_key_desc: "API key diterbitkan oleh admin Diskominfo. Ajukan permintaan untuk mendapatkan kunci akses aplikasi Anda.",
  api_generate_btn: "Ajukan Permintaan API Key",
  api_copy_btn: "Salin",
  api_quickstart_title: "Mulai Cepat",
  api_endpoints_title: "Daftar Endpoint",
  api_col_method: "Method",
  api_col_endpoint: "Endpoint",
  api_col_desc: "Deskripsi",
  ep1_desc: "Daftar semua sektor & indikator",
  ep2_desc: "Detail indikator per sektor",
  ep3_desc: "Data seluruh kecamatan",
  ep4_desc: "Tren waktu satu indikator",
  api_search_ph: 'Cari endpoint, mis. "guru" atau "kecamatan"…',
  api_all_sectors: "Semua Sektor",
  api_status_available: "Tersedia",
  api_status_soon: "Segera Hadir",
  api_no_endpoints_yet: "Endpoint sektor ini sedang disiapkan tim data.",
  api_params_title: "Parameter Query",
  api_param_required: "Wajib",
  api_param_optional: "Opsional",
  api_example_response_title: "Contoh Response",
  api_no_results: "Tidak ada endpoint yang cocok dengan pencarian.",
  exec_badge: "Akses Internal Pemerintah",
  exec_login_title: "Masuk ke Panel Admin",
  exec_login_sub: "Khusus admin Diskominfo Kota Bandung.",
  exec_email_label: "Email",
  exec_password_label: "Kata Sandi",
  exec_login_btn: "Masuk",
  exec_contact: "Hubungi tim teknis untuk permintaan akses admin.",
  exec_welcome: "Selamat datang",
  exec_role: "Administrator",
  exec_logout: "Keluar",
  exec_overview_title: "Panel Admin",
  admin_login_error: "Email atau password salah.",
  admin_api_keys_title: "API Key Aplikasi Eksternal",
  admin_col_label: "Label",
  admin_col_status: "Status",
  admin_col_last_used: "Terakhir Dipakai",
  admin_col_created: "Dibuat",
  admin_btn_revoke: "Cabut",
  admin_btn_activate: "Aktifkan",
  admin_btn_delete: "Hapus",
  admin_btn_edit: "Edit",
  admin_btn_cancel: "Batal",
  admin_new_key_ph: "Nama aplikasi/pemilik key…",
  admin_new_key_btn: "Buat API Key",
  admin_new_key_created: "Key baru dibuat, salin sekarang:",
  admin_status_active: "Aktif",
  admin_status_revoked: "Dicabut",
  admin_never_used: "Belum pernah",
  admin_data_sources_title: "Status Sinkronisasi Data",
  admin_col_dataset: "Dataset",
  admin_col_rows: "Jumlah Baris",
  admin_col_last_sync: "Terakhir Sync",
  admin_sync_stale: "Sudah lama",
  admin_visibility_title: "Visibilitas Sektor di Dashboard Publik",
  admin_col_sector: "Sektor",
  admin_visibility_shown: "Tampil",
  admin_visibility_hidden: "Disembunyikan",
  admin_site_settings_title: "Pengaturan Situs",
  admin_upload_logo_btn: "Unggah Logo",
  admin_save_btn: "Simpan",
  admin_saved_label: "Tersimpan",
  admin_sectors_title: "Sektor & Dashboard",
  admin_add_sector_btn: "Tambah Sektor",
  admin_manage_datasets_btn: "Kelola Dashboard",
  admin_datasets_for: "Dashboard untuk",
  admin_add_dataset_btn: "Tambah Dashboard",
  admin_api_requests_title: "Permintaan API",
  admin_col_name: "Nama",
  admin_col_institution: "Instansi",
  admin_col_email: "Email",
  admin_btn_approve: "Setujui",
  admin_btn_reject: "Tolak",
  footer_about_body: "Dashboard Bandung adalah kanal data terbuka resmi Kota Bandung, dikelola oleh Diskominfo untuk mendukung transparansi dan kebijakan berbasis data.",
  footer_links_title: "Tautan",
  footer_sectors_title: "Sektor",
  footer_contact_title: "Kontak",
  footer_rights: "© 2026 Dinas Komunikasi dan Informatika Kota Bandung",
  footer_disclaimer: "Data ilustratif — menunggu integrasi data resmi.",
};

export type I18nKey = keyof typeof I18N;
