/**
 * Placeholder / dummy data untuk Dashboard Bandung
 * Semua angka ILUSTRATIF — menunggu integrasi data resmi dari
 * Diskominfo / BPS / Disdukcapil Kota Bandung.
 *
 * Referensi: README.txt §Fidelity + .dc.html state data
 */

import type {
  CategorySummary,
  Dataset,
  Sector,
  KecamatanData,
  AgeBand,
  DinasBudget,
  ExecAlert,
  KecamatanSkor,
  SectorDetail,
  SectorDashboardItem,
} from "@/types/dataset";

// ─── Kategori (kompatibel dengan BE existing) ─────────────────────────────────

export const CATEGORY_PLACEHOLDERS: CategorySummary[] = [
  { slug: "kependudukan", name: "Kependudukan", description: "Jumlah, distribusi, dan komposisi penduduk per kecamatan.", datasetCount: 3 },
  { slug: "ekonomi", name: "Ekonomi", description: "Indikator ekonomi, UMKM, dan aktivitas perdagangan kota.", datasetCount: 2 },
  { slug: "kesehatan", name: "Kesehatan", description: "Fasilitas kesehatan, layanan puskesmas, dan data kasus.", datasetCount: 2 },
  { slug: "infrastruktur", name: "Infrastruktur", description: "Jalan, transportasi publik, dan fasilitas umum kota.", datasetCount: 2 },
  { slug: "lingkungan", name: "Lingkungan Hidup", description: "Kualitas udara, ruang terbuka hijau, dan pengelolaan sampah.", datasetCount: 2 },
  { slug: "pendidikan", name: "Pendidikan", description: "Sekolah, angka partisipasi, dan fasilitas pendidikan.", datasetCount: 2 },
];

export const DATASET_PLACEHOLDERS: Record<string, Dataset[]> = {
  kependudukan: [
    { id: 1, categoryId: 1, sourceId: "jumlah-penduduk-per-kecamatan", name: "Jumlah Penduduk per Kecamatan", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/jumlah-penduduk-per-kecamatan", syncFrequency: "monthly", lastSyncedAt: "2026-06-01T00:00:00.000Z" },
    { id: 2, categoryId: 1, sourceId: "kepadatan-penduduk", name: "Kepadatan Penduduk", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/kepadatan-penduduk", syncFrequency: "monthly", lastSyncedAt: "2026-06-01T00:00:00.000Z" },
    { id: 3, categoryId: 1, sourceId: "komposisi-usia-penduduk", name: "Komposisi Usia Penduduk", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/komposisi-usia-penduduk", syncFrequency: "monthly", lastSyncedAt: null },
  ],
  ekonomi: [
    { id: 4, categoryId: 2, sourceId: "data-umkm-kota-bandung", name: "Data UMKM Kota Bandung", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/data-umkm", syncFrequency: "monthly", lastSyncedAt: "2026-05-01T00:00:00.000Z" },
    { id: 5, categoryId: 2, sourceId: "pdrb-kota-bandung", name: "PDRB Kota Bandung", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/pdrb", syncFrequency: "monthly", lastSyncedAt: null },
  ],
  kesehatan: [
    { id: 6, categoryId: 3, sourceId: "fasilitas-kesehatan", name: "Fasilitas Kesehatan", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/fasilitas-kesehatan", syncFrequency: "monthly", lastSyncedAt: "2026-06-01T00:00:00.000Z" },
    { id: 7, categoryId: 3, sourceId: "kunjungan-puskesmas", name: "Kunjungan Puskesmas", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/kunjungan-puskesmas", syncFrequency: "weekly", lastSyncedAt: "2026-06-24T00:00:00.000Z" },
  ],
  infrastruktur: [
    { id: 8, categoryId: 4, sourceId: "kondisi-jalan", name: "Kondisi Jalan Kota", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/kondisi-jalan", syncFrequency: "monthly", lastSyncedAt: "2026-05-01T00:00:00.000Z" },
    { id: 9, categoryId: 4, sourceId: "trayek-transportasi-umum", name: "Trayek Transportasi Umum", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/trayek-transportasi", syncFrequency: "monthly", lastSyncedAt: null },
  ],
  lingkungan: [
    { id: 10, categoryId: 5, sourceId: "kualitas-udara", name: "Kualitas Udara (ISPU)", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/kualitas-udara", syncFrequency: "weekly", lastSyncedAt: "2026-06-24T00:00:00.000Z" },
    { id: 11, categoryId: 5, sourceId: "ruang-terbuka-hijau", name: "Ruang Terbuka Hijau", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/rth", syncFrequency: "monthly", lastSyncedAt: "2026-06-01T00:00:00.000Z" },
  ],
  pendidikan: [
    { id: 12, categoryId: 6, sourceId: "data-sekolah", name: "Data Sekolah", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/data-sekolah", syncFrequency: "monthly", lastSyncedAt: "2026-06-01T00:00:00.000Z" },
    { id: 13, categoryId: 6, sourceId: "angka-partisipasi-sekolah", name: "Angka Partisipasi Sekolah", sourceApiUrl: "https://opendata.bandung.go.id/api/datasets/angka-partisipasi", syncFrequency: "monthly", lastSyncedAt: null },
  ],
};

// ─── 8 Sektor untuk Home & Topics ─────────────────────────────────────────────

export const SECTORS: Sector[] = [
  {
    id: "kependudukan",
    code: "DUK",
    name: { id: "Kependudukan", en: "Demographics" },
    desc: { id: "Jumlah, kepadatan, dan sebaran penduduk Kota Bandung di 30 kecamatan.", en: "Population count, density and distribution across Bandung's 30 districts." },
    stat: { id: "2,52 Juta jiwa", en: "2.52 Million people" },
    color: "#1F5AA8",
    tint: "#E8F0FA",
    cluster: "sosial",
    spark: [2380, 2400, 2430, 2450, 2470, 2490, 2510, 2520],
    statusLabel: { id: "Data Terkini", en: "Up to date" },
    statusColor: "#1D8348",
    statusBg: "#E7F6ED",
  },
  {
    id: "ekonomi",
    code: "EKO",
    name: { id: "Ekonomi & UMKM", en: "Economy & SMEs" },
    desc: { id: "Indikator ekonomi, PDRB, dan data UMKM aktif Kota Bandung.", en: "Economic indicators, GDP, and active SME data for Bandung City." },
    stat: { id: "142.500 UMKM", en: "142,500 SMEs" },
    color: "#E8821E",
    tint: "#FDEEDD",
    cluster: "gov",
    spark: [130000, 133000, 136000, 138000, 140000, 141000, 142500, 142500],
    statusLabel: { id: "Perlu Perhatian", en: "Needs Attention" },
    statusColor: "#E8821E",
    statusBg: "#FDEEDD",
  },
  {
    id: "kesehatan",
    code: "KES",
    name: { id: "Kesehatan", en: "Health" },
    desc: { id: "Fasilitas kesehatan, kunjungan puskesmas, dan layanan kesehatan masyarakat.", en: "Health facilities, community health center visits, and public health services." },
    stat: { id: "73 Puskesmas", en: "73 Health Centers" },
    color: "#1D8348",
    tint: "#E7F6ED",
    cluster: "sosial",
    spark: [68, 69, 70, 71, 72, 72, 73, 73],
    statusLabel: { id: "Data Terkini", en: "Up to date" },
    statusColor: "#1D8348",
    statusBg: "#E7F6ED",
  },
  {
    id: "pendidikan",
    code: "PDK",
    name: { id: "Pendidikan", en: "Education" },
    desc: { id: "Sekolah, angka partisipasi sekolah, dan fasilitas pendidikan kota.", en: "Schools, school participation rate, and education facilities." },
    stat: { id: "10,8 Thn rata-rata", en: "10.8 Yrs avg schooling" },
    color: "#F0B429",
    tint: "#FDF3DA",
    cluster: "sosial",
    spark: [9.8, 10.0, 10.2, 10.4, 10.5, 10.6, 10.7, 10.8],
    statusLabel: { id: "Data Terkini", en: "Up to date" },
    statusColor: "#1D8348",
    statusBg: "#E7F6ED",
  },
  {
    id: "infrastruktur",
    code: "INF",
    name: { id: "Infrastruktur", en: "Infrastructure" },
    desc: { id: "Kondisi jalan, trayek transportasi umum, dan fasilitas umum kota.", en: "Road conditions, public transport routes, and urban facilities." },
    stat: { id: "82% jalan baik", en: "82% roads in good condition" },
    color: "#4C5D6B",
    tint: "#F4F6F9",
    cluster: "fisik",
    spark: [74, 76, 77, 78, 79, 80, 81, 82],
    statusLabel: { id: "Perlu Perhatian", en: "Needs Attention" },
    statusColor: "#E8821E",
    statusBg: "#FDEEDD",
  },
  {
    id: "lingkungan",
    code: "LNG",
    name: { id: "Lingkungan Hidup", en: "Environment" },
    desc: { id: "Kualitas udara ISPU, ruang terbuka hijau, dan pengelolaan sampah kota.", en: "Air quality (ISPU), green open spaces, and waste management." },
    stat: { id: "12 kec. udara baik", en: "12 districts clean air" },
    color: "#1D8348",
    tint: "#E7F6ED",
    cluster: "fisik",
    spark: [6, 7, 8, 9, 10, 11, 12, 12],
    statusLabel: { id: "Data Terkini", en: "Up to date" },
    statusColor: "#1D8348",
    statusBg: "#E7F6ED",
  },
  {
    id: "anggaran",
    code: "ANG",
    name: { id: "Anggaran & Keuangan", en: "Budget & Finance" },
    desc: { id: "Realisasi APBD, belanja per OPD, dan transparansi keuangan Pemkot Bandung.", en: "APBD realization, spending by department, and Bandung City financial transparency." },
    stat: { id: "78% realisasi APBD", en: "78% APBD realization" },
    color: "#1F5AA8",
    tint: "#E8F0FA",
    cluster: "gov",
    spark: [60, 63, 66, 68, 70, 73, 76, 78],
    statusLabel: { id: "On Track", en: "On Track" },
    statusColor: "#1D8348",
    statusBg: "#E7F6ED",
  },
  {
    id: "sosial",
    code: "SOS",
    name: { id: "Sosial & Kemasyarakatan", en: "Social Affairs" },
    desc: { id: "Data kemiskinan, bansos, penyandang disabilitas, dan layanan sosial kota.", en: "Poverty data, social aid, people with disabilities, and social services." },
    stat: { id: "3,2% tingkat kemiskinan", en: "3.2% poverty rate" },
    color: "#C0392B",
    tint: "#FBEAE8",
    cluster: "sosial",
    spark: [4.1, 3.9, 3.8, 3.7, 3.6, 3.4, 3.3, 3.2],
    statusLabel: { id: "Perlu Perhatian", en: "Needs Attention" },
    statusColor: "#E8821E",
    statusBg: "#FDEEDD",
  },
];

// ─── Tren populasi 2016–2026 ───────────────────────────────────────────────────

export const POPULATION_YEARS = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026];

export const POPULATION_TREND = [2380000, 2400000, 2420000, 2440000, 2450000, 2460000, 2475000, 2490000, 2500000, 2510000, 2520000];

// ─── 30 Kecamatan ─────────────────────────────────────────────────────────────

function densityColor(v: number): string {
  if (v < 9000) return "#DCEAFB";
  if (v < 12000) return "#AECBEE";
  if (v < 15000) return "#6FA0D8";
  if (v < 18000) return "#3D74B8";
  return "#1F4E8C";
}

function populationColor(p: number): string {
  if (p < 200000) return "#DCEAFB";
  if (p < 320000) return "#AECBEE";
  if (p < 440000) return "#6FA0D8";
  if (p < 560000) return "#3D74B8";
  return "#1F4E8C";
}

const rawKecamatan: [string, number, number][] = [
  ["Andir", 18500, 592000], ["Antapani", 15200, 412000], ["Arcamanik", 11800, 378000], ["Astanaanyar", 19800, 489000],
  ["Babakan Ciparay", 17600, 631000], ["Bandung Kidul", 10200, 254000], ["Bandung Kulon", 19200, 587000], ["Bandung Wetan", 9800, 142000],
  ["Batununggal", 16400, 548000], ["Bojongloa Kaler", 20100, 601000], ["Bojongloa Kidul", 15900, 423000], ["Buahbatu", 13700, 398000],
  ["Cibeunying Kaler", 12100, 289000], ["Cibeunying Kidul", 14300, 462000], ["Cibiru", 9600, 268000], ["Cicendo", 14800, 391000],
  ["Cidadap", 8200, 231000], ["Cinambo", 7100, 159000], ["Coblong", 13400, 481000], ["Gedebage", 6800, 187000],
  ["Kiaracondong", 18200, 527000], ["Lengkong", 13900, 342000], ["Mandalajati", 10900, 276000], ["Panyileukan", 8600, 193000],
  ["Rancasari", 11200, 318000], ["Regol", 16800, 356000], ["Sukajadi", 15100, 412000], ["Sukasari", 10600, 298000],
  ["Sumur Bandung", 12600, 124000], ["Ujung Berung", 12900, 309000],
];

const totalPop = rawKecamatan.reduce((sum, k) => sum + k[2], 0);

export const KECAMATAN_DATA: KecamatanData[] = rawKecamatan.map(([name, val, pop]) => ({
  name,
  val,
  pop,
  share: ((pop / totalPop) * 100).toFixed(1),
  color: densityColor(val),
  colorPop: populationColor(pop),
}));

// ─── Age bands (komposisi usia) ────────────────────────────────────────────────

export const AGE_BANDS: AgeBand[] = [
  { label: { id: "0–9", en: "0–9" },   male: 72, female: 68 },
  { label: { id: "10–19", en: "10–19" }, male: 78, female: 74 },
  { label: { id: "20–29", en: "20–29" }, male: 85, female: 82 },
  { label: { id: "30–39", en: "30–39" }, male: 80, female: 79 },
  { label: { id: "40–49", en: "40–49" }, male: 70, female: 69 },
  { label: { id: "50–59", en: "50–59" }, male: 58, female: 60 },
  { label: { id: "60+", en: "60+" },    male: 40, female: 48 },
];

// ─── Dinas budget (exec screen) ───────────────────────────────────────────────

export const DINAS_BUDGET: DinasBudget[] = [
  { name: { id: "Dinas Pendidikan", en: "Education Dept." }, pct: 85 },
  { name: { id: "Dinas Kesehatan", en: "Health Dept." }, pct: 78 },
  { name: { id: "Dinas PUPR", en: "Public Works" }, pct: 72 },
  { name: { id: "Dinas Sosial", en: "Social Affairs" }, pct: 65 },
  { name: { id: "Diskominfo", en: "ICT Dept." }, pct: 90 },
  { name: { id: "Dinas Lingkungan Hidup", en: "Environment Dept." }, pct: 58 },
];

// ─── Exec alerts ──────────────────────────────────────────────────────────────

export const EXEC_ALERTS: ExecAlert[] = [
  { mark: "!", color: "#C0392B", bg: "#FBEAE8", text: { id: "Realisasi anggaran Dinas Lingkungan Hidup di bawah target Q2 (58%).", en: "Environment Dept. budget realization below Q2 target (58%)." } },
  { mark: "↑", color: "#1D8348", bg: "#E7F6ED", text: { id: "Kunjungan puskesmas naik 12% dibanding bulan lalu.", en: "Health center visits up 12% vs. last month." } },
  { mark: "i", color: "#1F5AA8", bg: "#E8F0FA", text: { id: "Data sensus penduduk 2026 sedang diverifikasi oleh BPS.", en: "2026 census data currently being verified by BPS." } },
  { mark: "!", color: "#E8821E", bg: "#FDEEDD", text: { id: "3 kecamatan belum melaporkan data layanan sosial bulan Juni.", en: "3 districts haven't reported June social service data." } },
];

// ─── Kecamatan skor (exec screen) ─────────────────────────────────────────────

export const KECAMATAN_SKOR: KecamatanSkor[] = [
  { name: "Coblong", skor: 92 },
  { name: "Sukasari", skor: 90 },
  { name: "Cibeunying Kaler", skor: 89 },
  { name: "Lengkong", skor: 88 },
  { name: "Bandung Wetan", skor: 86 },
  { name: "Cidadap", skor: 85 },
  { name: "Panyileukan", skor: 63 },
  { name: "Bojongloa Kaler", skor: 60 },
];

// ─── Detail dummy per sektor (halaman /dashboard/[slug]) ──────────────────────

export const SECTOR_DETAILS: Record<string, SectorDetail> = {
  kependudukan: {
    kpis: [
      { label: { id: "Total Penduduk", en: "Total Population" }, value: "2.520.000" },
      { label: { id: "Kepadatan", en: "Density" }, value: "15.070/km²" },
      { label: { id: "Rasio Jenis Kelamin", en: "Sex Ratio" }, value: "99,2" },
      { label: { id: "Laju Pertumbuhan", en: "Growth Rate" }, value: "+0,68%", accent: "green" },
    ],
    trend: POPULATION_TREND,
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: { id: "Komposisi Usia Penduduk", en: "Population Age Composition" },
    breakdownLegendA: { id: "Laki-laki", en: "Male" },
    breakdownLegendB: { id: "Perempuan", en: "Female" },
    breakdownRows: AGE_BANDS.map((b) => ({ label: b.label, a: b.male, b: b.female })),
    kecamatanValueLabel: { id: "Jumlah Penduduk", en: "Population" },
    kecamatanUnit: "jiwa",
    kecamatanFactor: 1,
  },
  ekonomi: {
    kpis: [
      { label: { id: "UMKM Aktif", en: "Active SMEs" }, value: "142.500" },
      { label: { id: "PDRB", en: "GDP" }, value: "Rp 214,3 T" },
      { label: { id: "Pertumbuhan Ekonomi", en: "Economic Growth" }, value: "+5,4%", accent: "green" },
      { label: { id: "Pengangguran Terbuka", en: "Open Unemployment" }, value: "6,8%" },
    ],
    trend: [118000, 122000, 126000, 129000, 132000, 135000, 138000, 140000, 141500, 142000, 142500],
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: { id: "UMKM per Sektor Usaha", en: "SMEs by Business Sector" },
    breakdownLegendA: { id: "Formal", en: "Formal" },
    breakdownLegendB: { id: "Informal", en: "Informal" },
    breakdownRows: [
      { label: { id: "Kuliner", en: "Culinary" }, a: 62, b: 84 },
      { label: { id: "Fashion", en: "Fashion" }, a: 48, b: 72 },
      { label: { id: "Kerajinan", en: "Crafts" }, a: 35, b: 58 },
      { label: { id: "Jasa", en: "Services" }, a: 54, b: 66 },
      { label: { id: "Perdagangan", en: "Trade" }, a: 60, b: 90 },
      { label: { id: "Pertanian", en: "Agriculture" }, a: 22, b: 40 },
      { label: { id: "Teknologi", en: "Technology" }, a: 30, b: 20 },
    ],
    kecamatanValueLabel: { id: "Jumlah UMKM", en: "SME Count" },
    kecamatanUnit: "unit",
    kecamatanFactor: 0.24,
  },
  kesehatan: {
    kpis: [
      { label: { id: "Fasilitas Kesehatan", en: "Health Facilities" }, value: "73 Puskesmas" },
      { label: { id: "Kunjungan Bulanan", en: "Monthly Visits" }, value: "182.400" },
      { label: { id: "Angka Harapan Hidup", en: "Life Expectancy" }, value: "74,2 Thn" },
      { label: { id: "Angka Stunting", en: "Stunting Rate" }, value: "8,3%" },
    ],
    trend: [155000, 160000, 163000, 167000, 171000, 174000, 177000, 179000, 180500, 181500, 182400],
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: { id: "Jenis Layanan per Kelompok Usia", en: "Service Type by Age Group" },
    breakdownLegendA: { id: "Rawat Jalan", en: "Outpatient" },
    breakdownLegendB: { id: "Rawat Inap", en: "Inpatient" },
    breakdownRows: AGE_BANDS.map((b) => ({ label: b.label, a: b.male, b: Math.round(b.female * 0.3) })),
    kecamatanValueLabel: { id: "Kunjungan Layanan Kesehatan", en: "Health Service Visits" },
    kecamatanUnit: "kunjungan/bln",
    kecamatanFactor: 0.31,
  },
  pendidikan: {
    kpis: [
      { label: { id: "Jumlah Sekolah", en: "Number of Schools" }, value: "1.842" },
      { label: { id: "Rata-rata Lama Sekolah", en: "Mean Years of Schooling" }, value: "10,8 Thn" },
      { label: { id: "Angka Partisipasi Sekolah", en: "School Participation Rate" }, value: "98,7%" },
      { label: { id: "Guru Bersertifikasi", en: "Certified Teachers" }, value: "76%" },
    ],
    trend: [9.8, 10.0, 10.2, 10.3, 10.4, 10.5, 10.6, 10.6, 10.7, 10.7, 10.8],
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: { id: "Sekolah Negeri vs Swasta per Jenjang", en: "Public vs Private Schools by Level" },
    breakdownLegendA: { id: "Negeri", en: "Public" },
    breakdownLegendB: { id: "Swasta", en: "Private" },
    breakdownRows: [
      { label: { id: "PAUD", en: "Kindergarten" }, a: 22, b: 78 },
      { label: { id: "SD", en: "Elementary" }, a: 68, b: 32 },
      { label: { id: "SMP", en: "Middle" }, a: 55, b: 45 },
      { label: { id: "SMA", en: "High" }, a: 48, b: 52 },
      { label: { id: "SMK", en: "Vocational" }, a: 35, b: 65 },
      { label: { id: "PT", en: "University" }, a: 18, b: 82 },
    ],
    kecamatanValueLabel: { id: "Jumlah Sekolah", en: "School Count" },
    kecamatanUnit: "sekolah",
    kecamatanFactor: 0.062,
  },
  infrastruktur: {
    kpis: [
      { label: { id: "Kondisi Jalan Baik", en: "Roads in Good Condition" }, value: "82%", accent: "green" },
      { label: { id: "Total Panjang Jalan", en: "Total Road Length" }, value: "1.236 km" },
      { label: { id: "Trayek Angkutan Umum", en: "Public Transit Routes" }, value: "39 Trayek" },
      { label: { id: "Titik Lampu Jalan", en: "Street Light Points" }, value: "24.800" },
    ],
    trend: [74, 76, 77, 78, 79, 80, 80, 81, 81, 82, 82],
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: { id: "Kondisi per Jenis Infrastruktur", en: "Condition by Infrastructure Type" },
    breakdownLegendA: { id: "Baik", en: "Good" },
    breakdownLegendB: { id: "Rusak", en: "Damaged" },
    breakdownRows: [
      { label: { id: "Jln. Nasional", en: "National Rd" }, a: 91, b: 9 },
      { label: { id: "Jln. Provinsi", en: "Provincial Rd" }, a: 85, b: 15 },
      { label: { id: "Jln. Kota", en: "City Rd" }, a: 78, b: 22 },
      { label: { id: "Jln. Lingk.", en: "Local Rd" }, a: 66, b: 34 },
      { label: { id: "Jembatan", en: "Bridges" }, a: 88, b: 12 },
      { label: { id: "Trotoar", en: "Sidewalks" }, a: 60, b: 40 },
      { label: { id: "Drainase", en: "Drainage" }, a: 70, b: 30 },
    ],
    kecamatanValueLabel: { id: "Panjang Jalan", en: "Road Length" },
    kecamatanUnit: "km",
    kecamatanFactor: 0.021,
  },
  lingkungan: {
    kpis: [
      { label: { id: "Kualitas Udara Baik", en: "Good Air Quality" }, value: "12 Kec." },
      { label: { id: "Ruang Terbuka Hijau", en: "Green Open Space" }, value: "12,6%" },
      { label: { id: "Sampah Terkelola", en: "Waste Managed" }, value: "1.450 ton/hari" },
      { label: { id: "Titik Bank Sampah", en: "Waste Bank Points" }, value: "218", accent: "green" },
    ],
    trend: [6, 7, 8, 9, 10, 10, 11, 11, 12, 12, 12],
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: { id: "Pengelolaan Sampah per Wilayah", en: "Waste Management by Area" },
    breakdownLegendA: { id: "Organik", en: "Organic" },
    breakdownLegendB: { id: "Anorganik", en: "Inorganic" },
    breakdownRows: [
      { label: { id: "Wil. 1", en: "Zone 1" }, a: 58, b: 42 },
      { label: { id: "Wil. 2", en: "Zone 2" }, a: 55, b: 45 },
      { label: { id: "Wil. 3", en: "Zone 3" }, a: 61, b: 39 },
      { label: { id: "Wil. 4", en: "Zone 4" }, a: 50, b: 50 },
      { label: { id: "Wil. 5", en: "Zone 5" }, a: 64, b: 36 },
      { label: { id: "Wil. 6", en: "Zone 6" }, a: 47, b: 53 },
      { label: { id: "Wil. 7", en: "Zone 7" }, a: 53, b: 47 },
    ],
    kecamatanValueLabel: { id: "Volume Sampah Terkelola", en: "Waste Volume Managed" },
    kecamatanUnit: "ton/hari",
    kecamatanFactor: 0.0023,
  },
  anggaran: {
    kpis: [
      { label: { id: "Realisasi APBD", en: "Budget Realization" }, value: "78%", accent: "green" },
      { label: { id: "Total APBD", en: "Total Budget" }, value: "Rp 8,9 T" },
      { label: { id: "Belanja Modal", en: "Capital Expenditure" }, value: "Rp 1,6 T" },
      { label: { id: "SILPA", en: "Budget Surplus" }, value: "Rp 412 M" },
    ],
    trend: [60, 63, 66, 68, 70, 72, 73, 75, 76, 77, 78],
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: { id: "Realisasi Anggaran per Dinas", en: "Budget Realization by Department" },
    breakdownLegendA: { id: "Terealisasi", en: "Realized" },
    breakdownLegendB: { id: "Sisa", en: "Remaining" },
    breakdownRows: DINAS_BUDGET.map((d) => ({ label: d.name, a: d.pct, b: 100 - d.pct })),
    kecamatanValueLabel: { id: "Belanja per Kecamatan", en: "Spending per District" },
    kecamatanUnit: "Rp Juta",
    kecamatanFactor: 0.42,
  },
  sosial: {
    kpis: [
      { label: { id: "Tingkat Kemiskinan", en: "Poverty Rate" }, value: "3,2%" },
      { label: { id: "Penerima Bansos", en: "Social Aid Recipients" }, value: "48.200 KK" },
      { label: { id: "Penyandang Disabilitas", en: "People with Disabilities" }, value: "12.400 Jiwa" },
      { label: { id: "Panti Sosial Aktif", en: "Active Social Homes" }, value: "34" },
    ],
    trend: [4.1, 3.9, 3.8, 3.7, 3.6, 3.5, 3.4, 3.3, 3.3, 3.2, 3.2],
    trendPeriods: POPULATION_YEARS,
    breakdownTitle: { id: "Jenis Bantuan Sosial per Kategori", en: "Social Aid Type by Category" },
    breakdownLegendA: { id: "Tunai", en: "Cash" },
    breakdownLegendB: { id: "Non-Tunai", en: "Non-Cash" },
    breakdownRows: [
      { label: { id: "Lansia", en: "Elderly" }, a: 62, b: 38 },
      { label: { id: "Difabel", en: "Disability" }, a: 55, b: 45 },
      { label: { id: "Anak", en: "Children" }, a: 40, b: 60 },
      { label: { id: "PKH", en: "PKH" }, a: 70, b: 30 },
      { label: { id: "BPNT", en: "BPNT" }, a: 15, b: 85 },
      { label: { id: "Yatim Piatu", en: "Orphans" }, a: 48, b: 52 },
      { label: { id: "Korban Bencana", en: "Disaster Victims" }, a: 80, b: 20 },
    ],
    kecamatanValueLabel: { id: "Penerima Bansos", en: "Social Aid Recipients" },
    kecamatanUnit: "KK",
    kecamatanFactor: 0.019,
  },
};

// ─── Dashboard/laporan per sektor (halaman Eksplorasi Dashboard) ──────────────
// Satu sektor bisa punya banyak "dashboard" — meniru struktur Dashboard Jabar.

export const SECTOR_DASHBOARDS: Record<string, SectorDashboardItem[]> = {
  kependudukan: [
    { title: { id: "Jumlah & Kepadatan Penduduk per Kecamatan", en: "Population & Density by District" }, year: 2026, views: 8420 },
    { title: { id: "Komposisi Usia & Jenis Kelamin", en: "Age & Sex Composition" }, year: 2026, views: 5310 },
    { title: { id: "Laju Pertumbuhan Penduduk 2016–2026", en: "Population Growth Rate 2016–2026" }, year: 2026, views: 3980 },
  ],
  ekonomi: [
    { title: { id: "Dashboard Rekomendasi UMKM", en: "SME Recommendation Dashboard" }, year: 2026, views: 6210 },
    { title: { id: "Sebaran UMKM per Sektor Usaha", en: "SMEs by Business Sector" }, year: 2025, views: 4720 },
    { title: { id: "PDRB & Pertumbuhan Ekonomi", en: "GDP & Economic Growth" }, year: 2025, views: 3150 },
    { title: { id: "Tingkat Pengangguran Terbuka", en: "Open Unemployment Rate" }, year: 2024, views: 2890 },
  ],
  kesehatan: [
    { title: { id: "Sebaran Fasilitas Kesehatan", en: "Health Facility Distribution" }, year: 2026, views: 5540 },
    { title: { id: "Kunjungan Puskesmas per Kecamatan", en: "Health Center Visits by District" }, year: 2026, views: 4130 },
    { title: { id: "Angka Stunting & Harapan Hidup", en: "Stunting Rate & Life Expectancy" }, year: 2025, views: 2670 },
  ],
  pendidikan: [
    { title: { id: "Jumlah Sekolah, Guru, Peserta Didik (SMP) Bandung", en: "Number of Schools, Teachers, Students (Middle School) Bandung" }, year: 2026, views: 7680 },
  ],
  infrastruktur: [
    { title: { id: "Kondisi Jalan per Jenis & Kecamatan", en: "Road Condition by Type & District" }, year: 2025, views: 3870 },
    { title: { id: "Trayek & Rute Angkutan Umum", en: "Public Transit Routes" }, year: 2025, views: 2650 },
    { title: { id: "Sebaran Titik Lampu Jalan", en: "Street Lighting Distribution" }, year: 2024, views: 1740 },
  ],
  lingkungan: [
    { title: { id: "Indeks Kualitas Udara (ISPU) Harian", en: "Daily Air Quality Index (ISPU)" }, year: 2026, views: 4980 },
    { title: { id: "Capaian Penanganan Sampah per Wilayah", en: "Waste Handling Achievement by Area" }, year: 2026, views: 3420 },
    { title: { id: "Sebaran Ruang Terbuka Hijau", en: "Green Open Space Distribution" }, year: 2025, views: 2380 },
  ],
  anggaran: [
    { title: { id: "Realisasi APBD per Dinas", en: "Budget Realization by Department" }, year: 2026, views: 5120 },
    { title: { id: "Belanja Modal & Operasional", en: "Capital & Operational Spending" }, year: 2025, views: 2960 },
  ],
  sosial: [
    { title: { id: "Sebaran Penerima Bantuan Sosial", en: "Social Aid Recipient Distribution" }, year: 2026, views: 3640 },
    { title: { id: "Tingkat Kemiskinan per Kecamatan", en: "Poverty Rate by District" }, year: 2026, views: 2980 },
    { title: { id: "Data Penyandang Disabilitas", en: "People with Disabilities Data" }, year: 2025, views: 1650 },
  ],
};

// ─── i18n strings ─────────────────────────────────────────────────────────────

export const I18N = {
  id: {
    utility_text: "Portal Resmi Pemerintah Kota Bandung",
    nav_home: "Beranda",
    nav_topics: "Topik & Sektor",
    nav_api: "Data API",
    btn_exec: "Login Eksekutif",
    tagline: "Satu Data, Satu Bandung",
    search_ph: 'Cari indikator, mis. "kepadatan penduduk"…',
    hero_eyebrow: "Portal Data Terbuka Kota Bandung",
    hero_title: "Dashboard Bandung",
    hero_sub: "Satu kanal angka, metrik, dan visualisasi data resmi Kota Bandung untuk warga dan pengambil kebijakan.",
    kpi_pop: "Populasi",
    kpi_area: "Luas Wilayah",
    kpi_kec: "Kecamatan",
    kpi_kel: "Kelurahan",
    kpi_pop_val: "2,52 Juta",
    kpi_area_val: "167,3 km²",
    kpi_kec_val: "30",
    kpi_kel_val: "151",
    sectors_title: "Jelajahi Data per Sektor",
    sectors_sub: "Pilih sektor untuk melihat indikator, tren, dan sebaran datanya.",
    detail_link: "Lihat semua",
    highlight_title: "Sorotan Data Minggu Ini",
    chart_trend_title: "Tren Jumlah Penduduk 2016–2026",
    growth_label: "Laju Pertumbuhan/th",
    cta_title: "Punya data yang ingin dipublikasikan?",
    cta_body: "Diskominfo Kota Bandung membuka kanal integrasi data untuk OPD dan mitra.",
    cta_btn: "Hubungi Kami",
    breadcrumb_home: "Beranda",
    breadcrumb_topics: "Topik & Sektor",
    topics_h1: "Topik & Sektor",
    topics_sub: "Jelajahi seluruh indikator resmi Kota Bandung, dikelompokkan per sektor.",
    topics_search_ph: "Cari dashboard…",
    filter_semua: "Semua",
    filter_gov: "Pemerintahan & Ekonomi",
    filter_sosial: "Manusia & Sosial",
    filter_fisik: "Fisik & Lingkungan",
    sidebar_all_topics: "Semua Topik",
    dashboard_views: "dilihat",
    detail_link2: "Lihat Detail",
    request_title: "Tidak menemukan data yang dicari?",
    request_body: "Ajukan permintaan data ke Diskominfo Kota Bandung, tim kami akan menindaklanjuti dalam 3 hari kerja.",
    request_btn: "Ajukan Permintaan Data",
    detail_title: "Kependudukan",
    detail_desc: "Jumlah, kepadatan, dan sebaran penduduk Kota Bandung di 30 kecamatan.",
    detail_source: "Sumber",
    detail_updated: "Diperbarui",
    detail_download: "Unduh Data",
    source_name: "Disdukcapil Kota Bandung",
    updated_date: "Jun 2026",
    kpi_total_pop: "Total Penduduk",
    kpi_density: "Kepadatan",
    kpi_sexratio: "Rasio Jenis Kelamin",
    kpi_growth: "Laju Pertumbuhan",
    chart_age_title: "Komposisi Usia Penduduk",
    male_label: "Laki-laki",
    female_label: "Perempuan",
    related_title: "Indikator Terkait",
    map_dist_title: "Sebaran Penduduk per Kecamatan",
    table_title: "Data per Kecamatan",
    table_col_kec: "Kecamatan",
    table_col_pop: "Penduduk",
    table_col_density: "Kepadatan (jiwa/km²)",
    table_col_share: "% dari Total",
    api_h1: "Akses Data via API",
    api_sub: "Ambil data Dashboard Bandung secara terprogram untuk aplikasi, riset, atau integrasi sistem Anda.",
    api_key_title: "Kunci API Anda",
    api_key_desc: "Gunakan kunci ini pada header Authorization di setiap permintaan.",
    api_generate_btn: "Buat Kunci Baru",
    api_copy_btn: "Salin",
    api_quickstart_title: "Mulai Cepat",
    api_endpoints_title: "Daftar Endpoint",
    api_col_method: "Method",
    api_col_endpoint: "Endpoint",
    api_col_desc: "Deskripsi",
    api_rate_title: "Batas Penggunaan",
    api_rate_desc: "1.000 permintaan/hari untuk akses gratis. Hubungi Diskominfo untuk kuota lebih besar.",
    api_docs_btn: "Buka Dokumentasi Lengkap",
    ep1_desc: "Daftar semua sektor & indikator",
    ep2_desc: "Detail indikator per sektor",
    ep3_desc: "Data seluruh kecamatan",
    ep4_desc: "Tren waktu satu indikator",
    api_search_ph: "Cari endpoint, mis. \"guru\" atau \"kecamatan\"…",
    api_all_sectors: "Semua Sektor",
    api_status_available: "Tersedia",
    api_status_soon: "Segera Hadir",
    api_no_endpoints_yet: "Endpoint sektor ini sedang disiapkan tim data.",
    api_params_title: "Parameter Query",
    api_param_required: "Wajib",
    api_param_optional: "Opsional",
    api_example_response_title: "Contoh Response",
    api_no_results: "Tidak ada endpoint yang cocok dengan pencarian.",
    exec_badge: "Akses Internal Pemerintah",
    exec_login_title: "Masuk ke Dashboard Eksekutif",
    exec_login_sub: "Khusus pegawai Pemerintah Kota Bandung dan Diskominfo.",
    exec_email_label: "Email / NIP",
    exec_password_label: "Kata Sandi",
    exec_login_btn: "Masuk",
    exec_demo_btn: "Masuk sebagai Demo",
    exec_contact: "Hubungi admin untuk permintaan akses.",
    exec_welcome: "Selamat datang",
    exec_role: "Kepala Bidang Data & Statistik",
    exec_logout: "Keluar",
    exec_overview_title: "Ringkasan Kinerja Seluruh Sektor",
    exec_budget_title: "Realisasi Anggaran per Dinas",
    exec_alerts_title: "Notifikasi & Peringatan",
    exec_score_title: "Skor Kinerja per Kecamatan",
    exec_export_btn: "Unduh Laporan Eksekutif (PDF)",
    footer_about_body: "Dashboard Bandung adalah kanal data terbuka resmi Kota Bandung, dikelola oleh Diskominfo untuk mendukung transparansi dan kebijakan berbasis data.",
    footer_links_title: "Tautan",
    footer_sectors_title: "Sektor",
    footer_contact_title: "Kontak",
    footer_rights: "© 2026 Dinas Komunikasi dan Informatika Kota Bandung",
    footer_disclaimer: "Data ilustratif — menunggu integrasi data resmi.",
  },
  en: {
    utility_text: "Official Portal of Bandung City Government",
    nav_home: "Home",
    nav_topics: "Topics & Sectors",
    nav_api: "Data API",
    btn_exec: "Executive Login",
    tagline: "One Data, One Bandung",
    search_ph: 'Search an indicator, e.g. "population density"…',
    hero_eyebrow: "Bandung City Open Data Portal",
    hero_title: "Dashboard Bandung",
    hero_sub: "One channel for the official figures, metrics, and data visualizations of Bandung City — for residents and policymakers.",
    kpi_pop: "Population",
    kpi_area: "Area",
    kpi_kec: "Districts",
    kpi_kel: "Villages",
    kpi_pop_val: "2.52 Million",
    kpi_area_val: "167.3 km²",
    kpi_kec_val: "30",
    kpi_kel_val: "151",
    sectors_title: "Explore Data by Sector",
    sectors_sub: "Choose a sector to see its indicators, trends and distribution.",
    detail_link: "See all",
    highlight_title: "This Week's Data Highlight",
    chart_trend_title: "Population Trend 2016–2026",
    growth_label: "Growth Rate/yr",
    cta_title: "Have data you'd like published?",
    cta_body: "Diskominfo Bandung welcomes data integration from city agencies and partners.",
    cta_btn: "Contact Us",
    breadcrumb_home: "Home",
    breadcrumb_topics: "Topics & Sectors",
    topics_h1: "Topics & Sectors",
    topics_sub: "Explore all of Bandung's official indicators, grouped by sector.",
    topics_search_ph: "Search dashboard…",
    filter_semua: "All",
    filter_gov: "Government & Economy",
    filter_sosial: "People & Society",
    filter_fisik: "Physical & Environment",
    sidebar_all_topics: "All Topics",
    dashboard_views: "views",
    detail_link2: "View Detail",
    request_title: "Can't find the data you need?",
    request_body: "Submit a data request to Diskominfo Bandung — our team responds within 3 business days.",
    request_btn: "Submit Data Request",
    detail_title: "Demographics",
    detail_desc: "Population count, density and distribution across Bandung's 30 districts.",
    detail_source: "Source",
    detail_updated: "Updated",
    detail_download: "Download Data",
    source_name: "Bandung Civil Registry Office",
    updated_date: "Jun 2026",
    kpi_total_pop: "Total Population",
    kpi_density: "Density",
    kpi_sexratio: "Sex Ratio",
    kpi_growth: "Growth Rate",
    chart_age_title: "Population Age Composition",
    male_label: "Male",
    female_label: "Female",
    related_title: "Related Indicators",
    map_dist_title: "Population Distribution by District",
    table_title: "Data by District",
    table_col_kec: "District",
    table_col_pop: "Population",
    table_col_density: "Density (people/km²)",
    table_col_share: "% of Total",
    api_h1: "Access Data via API",
    api_sub: "Pull Dashboard Bandung data programmatically for your app, research, or system integration.",
    api_key_title: "Your API Key",
    api_key_desc: "Use this key in the Authorization header on every request.",
    api_generate_btn: "Generate New Key",
    api_copy_btn: "Copy",
    api_quickstart_title: "Quick Start",
    api_endpoints_title: "Endpoints",
    api_col_method: "Method",
    api_col_endpoint: "Endpoint",
    api_col_desc: "Description",
    api_rate_title: "Usage Limits",
    api_rate_desc: "1,000 requests/day on the free tier. Contact Diskominfo for a higher quota.",
    api_docs_btn: "Open Full Documentation",
    ep1_desc: "List all sectors & indicators",
    ep2_desc: "Indicator detail per sector",
    ep3_desc: "Data for all districts",
    ep4_desc: "Time trend for one indicator",
    api_search_ph: 'Search endpoint, e.g. "teacher" or "district"…',
    api_all_sectors: "All Sectors",
    api_status_available: "Available",
    api_status_soon: "Coming Soon",
    api_no_endpoints_yet: "This sector's endpoints are being prepared by the data team.",
    api_params_title: "Query Parameters",
    api_param_required: "Required",
    api_param_optional: "Optional",
    api_example_response_title: "Example Response",
    api_no_results: "No endpoints match your search.",
    exec_badge: "Internal Government Access",
    exec_login_title: "Sign in to Executive Dashboard",
    exec_login_sub: "For Bandung City Government and Diskominfo staff only.",
    exec_email_label: "Email / Employee ID",
    exec_password_label: "Password",
    exec_login_btn: "Sign In",
    exec_demo_btn: "Continue as Demo",
    exec_contact: "Contact admin to request access.",
    exec_welcome: "Welcome",
    exec_role: "Head of Data & Statistics",
    exec_logout: "Log Out",
    exec_overview_title: "All-Sector Performance Overview",
    exec_budget_title: "Budget Realization by Department",
    exec_alerts_title: "Alerts & Notifications",
    exec_score_title: "Performance Score by District",
    exec_export_btn: "Download Executive Report (PDF)",
    footer_about_body: "Dashboard Bandung is the official open-data channel for Bandung City, run by Diskominfo to support transparency and data-driven policy.",
    footer_links_title: "Links",
    footer_sectors_title: "Sectors",
    footer_contact_title: "Contact",
    footer_rights: "© 2026 Bandung City Communication & Informatics Office",
    footer_disclaimer: "Illustrative data — pending official integration.",
  },
} as const;

export type I18nKey = keyof typeof I18N.id;
